### ISSUE TITLE
Component Does Not Load

### ISSUE THREAD

**Issue by snepple** [ZacheryThomas/homeassistant-smartrent#1]
The Component Does Not Load.  Bleow is the error from the log when starting Home Assistant.

Logger: homeassistant.components.lock
Source: custom_components/smartrent/lock.py:31
Integration: Lock (documentation, issues)
First occurred: 9:15:02 PM (1 occurrences)
Last logged: 9:15:02 PM

Error while setting up smartrent platform for lock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/smartrent/lock.py", line 31, in async_setup_platform
    sr = await async_login(username, password)
  File "/usr/local/lib/python3.9/site-packages/smartrent/api.py", line 91, in async_login
    await smart_rent_api.async_fetch_devices()
  File "/usr/local/lib/python3.9/site-packages/smartrent/api.py", line 55, in async_fetch_devices
    device_object._fetch_state_helper(device)
  File "/usr/local/lib/python3.9/site-packages/smartrent/thermostat.py", line 147, in _fetch_state_helper
    self._fan_mode = attrs['fan_mode']
KeyError: 'fan_mode'

**Comment by ZacheryThomas** [comment]
Hello! Could you by chance run this and provide me with the results? You will have to fill in your email and pass in the top of the script.

I think your SmartRent setup in your apartment may be different than mine. This will help me determine what devices you have on your install and what settings they will have enabled.

```bash
python -c """
email = 'YOUR EMAIL HERE'
password = 'YOUR PASSWORD HERE'

SMARTRENT_BASE_URI     = 'https://control.smartrent.com/api/v2/'
SMARTRENT_SESSIONS_URI = SMARTRENT_BASE_URI + 'sessions'
SMARTRENT_HUBS_URI     = SMARTRENT_BASE_URI + 'hubs'
SMARTRENT_HUBS_ID_URI  = SMARTRENT_BASE_URI + 'hubs/{}/devices'

import requests
import json

res = requests.post(SMARTRENT_SESSIONS_URI, json={
    'email': email,
    'password': password
}).json()


token = res['access_token']
headers={
    'authorization': f'Bearer {token}'
}

hubs = requests.get(
    SMARTRENT_HUBS_URI,
    headers=headers
).json()

for hub in hubs:
    devices = requests.get(
        SMARTRENT_HUBS_ID_URI.format(hub['id']),
        headers=headers
    ).json()

    output = json.dumps(devices, indent=4)
    print(output)
"""
```

**Comment by snepple** [comment]
[
    {
        "attributes": [
            {
                "last_read_at": "2021-12-26T12:59:59Z",
                "name": "heating_setpoint",
                "state": "61"
            },
            {
                "last_read_at": "2021-12-26T12:01:57Z",
                "name": "mode",
                "state": "heat"
            },
            {
                "last_read_at": "2021-12-26T16:39:30Z",
                "name": "current_temp",
                "state": "64"
            },
            {
                "last_read_at": "2021-12-26T13:31:44Z",
                "name": "current_humidity",
                "state": "49"
            },
            {
                "last_read_at": "2021-12-26T12:15:46Z",
                "name": "cooling_setpoint",
                "state": "78"
            }
        ],
        "battery_level": 40,
        "battery_powered": true,
        "icon": null,
        "id": 1913401,
        "inserted_at": "2021-03-12T19:20:36",
        "name": "Thermostat",
        "online": true,
        "pending_update": false,
        "primary_lock": false,
        "room": {
            "hub_id": 268596,
            "icon": null,
            "id": 234530,
            "inserted_at": "2021-03-12T19:14:59.190532",
            "name": "No Room",
            "updated_at": "2021-03-12T19:14:59.190532"
        },
        "show_on_dashboard": true,
        "type": "thermostat",
        "updated_at": "2021-12-26T11:31:10",
        "valid_config": true,
        "warning": false
    },
    {
        "attributes": [
            {
                "name": "access_codes_supported",
                "state": "true"
            },
            {
                "last_read_at": "2021-12-26T16:45:58Z",
                "name": "locked",
                "state": "false"
            },
            {
                "last_read_at": "2021-12-26T16:45:58Z",
                "name": "notifications",
                "state": "KEY_OR_THUMBTURN_UNLOCK"
            }
        ],
        "battery_level": 72,
        "battery_powered": true,
        "icon": null,
        "id": 1913378,
        "inserted_at": "2021-03-12T19:16:29",
        "name": "Front Door - Lock",
        "online": true,
        "pending_update": false,
        "primary_lock": true,
        "room": {
            "hub_id": 268596,
            "icon": null,
            "id": 234530,
            "inserted_at": "2021-03-12T19:14:59.190532",
            "name": "No Room",
            "updated_at": "2021-03-12T19:14:59.190532"
        },
        "show_on_dashboard": true,
        "type": "entry_control",
        "updated_at": "2021-12-26T18:20:40",
        "valid_config": true,
        "warning": false
    }
]

**Comment by ZacheryThomas** [comment]
Thanks! I think I was able to fix the issue.

Try getting the latest code and start up homeassistant again. Lemmie know if it ends up working out for you!

**Comment by snepple** [comment]
The latest code has resolved the issue.
