### ISSUE TITLE
Thermostat Automation

### ISSUE THREAD

**Issue by CardcaptorRLH85** [ZacheryThomas/homeassistant-smartrent#13]
I'm trying to automate a home/away presence sensing mode in HA with my SmartRent thermostat. I'm only seeing "Change HVAC Mode on Thermostat" as an option and nothing to change the temperature.  Am I doing something wrong or is this a bug or an incomplete feature?

**Comment by ZacheryThomas** [comment]
Hi! Im assumin you are talking about writing an action in a new automation. You should be able to get your desired result by using a `Call Service` action. Then you can then search for the `Climate: Set temperature` service type. After that you should kinda get a similar view like I have here where you can set temps & thermostat modes:
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/15793830/213591754-24379a69-1f3c-4e71-b496-ce7b112a55dd.png">

**Comment by CardcaptorRLH85** [comment]
Thanks for the help!  I have one more issue though, I only get the first Temperature option.  I'm not seeing the high or low targets here even though I have those options in the SmartRent app itself.
![2023-01-19 20_25_21-](https://user-images.githubusercontent.com/1551856/213598523-1127aa36-7c32-4d33-8bfb-63e8f8ac7828.png)
