### ISSUE TITLE
Does not seem to support two factor authentication. 

### ISSUE THREAD

**Issue by dkitsov** [ZacheryThomas/homeassistant-smartrent#16]
Not a bug per se, but this integration does not work, If a two factor authentication is enabled on smart home website.

**Comment by ZacheryThomas** [comment]
@dkitsov thanks for reaching out. I'm looking into this! Hopefully I can get something in place soon-ish.

**Comment by ZacheryThomas** [comment]
@dkitsov I added this feature in the latest release: https://github.com/ZacheryThomas/homeassistant-smartrent/releases/tag/v0.4.0

Give it a shot if you have a chance!

**Comment by dkitsov** [comment]
Looks good so far two days later.

**Comment by AD-Wright** [comment]
Is two-factor only required once, or does it have to be entered every time HA restarts?

**Comment by ZacheryThomas** [comment]
You gotta enter in a new 2fa code every time home assistant restartsOn Feb 19, 2024, at 10:07 PM, AD-Wright ***@***.***> wrote:﻿
Is two-factor only required once, or does it have to be entered every time HA restarts?
