### ISSUE TITLE
Re-enter Password

### ISSUE THREAD

**Issue by matt-luni** [ZacheryThomas/homeassistant-smartrent#17]
I can't seem to find a way to re-enter my log in credentials. other than removing and re-adding the integration, which would (I think) also require renaming all of the devices/entities again.

Is there a place to change the password that I'm missing? Or is this a feature request?

**Comment by matt-luni** [comment]
Thanks for the reply, I was able to update it and things are working again.

**Comment by ZacheryThomas** [comment]
I added a way to redo auth when a password change occurs & your integration breaks. Is out now the [latest release](https://github.com/ZacheryThomas/homeassistant-smartrent/releases/tag/v0.4.0). Haha you probs don't need it anymore, but just for the future!
