### ISSUE TITLE
Setup failed for custom integration smartrent: Requirements for smartrent not found: ['smartrent.py==0.4.3']

### ISSUE THREAD

**Issue by TeckPete** [ZacheryThomas/homeassistant-smartrent#22]
![Capture85](https://github.com/ZacheryThomas/homeassistant-smartrent/assets/35778227/ce68e6f9-1724-4ad3-9747-6b91acb30a18)
[home-assistant_2023-11-03T21-16-01.005Z.log](https://github.com/ZacheryThomas/homeassistant-smartrent/files/13254876/home-assistant_2023-11-03T21-16-01.005Z.log)

**Comment by ZacheryThomas** [comment]
Hmm these errors are generally caused by some network instability or outage. Have things resolved or are you still seeing the same error occuring?

**Comment by TeckPete** [comment]
Hey thanks for your response! I was just going to delete this. I ended up re-installing HA. I think it was a problem with HACS.
