### ISSUE TITLE
Error appearing in home assistant logs

### ISSUE THREAD

**Issue by sam2332** [ZacheryThomas/homeassistant-smartrent#24]
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:367
integration: Climate (documentation, issues)
First occurred: 1:57:02 AM (1 occurrences)
Last logged: 1:57:02 AM

Entity None (<class 'custom_components.smartrent.climate.SmartrentThermostat'>) implements HVACMode(s): heat, cool, off, heat_cool and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/ZacheryThomas/homeassistant-smartrent/issues

**Comment by ZacheryThomas** [comment]
Should be fixed when you download the latest release!
https://github.com/ZacheryThomas/homeassistant-smartrent/releases/tag/v0.4.6
