### ISSUE TITLE
Sensor's not updating

### ISSUE THREAD

**Issue by sam2332** [ZacheryThomas/homeassistant-smartrent#25]
I'm having issues where my sensors are not updated I don't know if it's related to my home assistant instance or if it's related to this plug-in itself

**Comment by sam2332** [comment]
It is possible this is related to the smart rent company, their app is not working very well right now either

**Comment by ZacheryThomas** [comment]
Hmm, I haven't noticed anything out of the ordinary for my personal homeassistant install.

Can you describe more about the behavior you are seeing? Is it all sensors related to SmartRent or just one particular sensor? Any errors in the logs (besides [this one](https://github.com/ZacheryThomas/homeassistant-smartrent/issues/24))?

**Comment by sam2332** [comment]
I believe that the thermostat is working correctly the issue appears to be the sensor for lock is locked and the lock Device itself not updating the lock status I'm sorry that it took me so long to get back to you 

Having this issue and the only solution I have is forcefully calling the update entity function in a service automation

**Comment by sam2332** [comment]
![Screenshot_20240421-182533](https://github.com/ZacheryThomas/homeassistant-smartrent/assets/945622/75600612-1fb3-4f8e-b5db-4b3a76e92fff)
![Screenshot_20240421-182538](https://github.com/ZacheryThomas/homeassistant-smartrent/assets/945622/cd7ff353-9aca-4c94-b6df-b980fa03957c)

**Comment by sam2332** [comment]
So if I use home assistant to lock the front door it enters an entry into the event log but it does not update the user interface for the smart rent application. 

I think there's a problem where smart rent themselves are not correctly displaying or updating the value maybe we can extract the value from the activity list instead

**Comment by ZacheryThomas** [comment]
@sam2332 This may be a little late, but I recently had this issue too. This is an issue where your lock no longer sends info to your hub. I had to call Smartrent and they walked me through re-pairing the lock with the hub and after that things worked like normal.

**Comment by sam2332** [comment]
> @sam2332 This may be a little late, but I recently had this issue too. This is an issue where your lock no longer sends info to your hub. I had to call Smartrent and they walked me through re-pairing the lock with the hub and after that things worked like normal.

Thank you
