### ISSUE TITLE
Issue in home assistant logs - async_add_job

### ISSUE THREAD

**Issue by sam2332** [ZacheryThomas/homeassistant-smartrent#27]
Home assistant log had the following error for smartrent

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184
First occurred: 9:42:22 AM (10 occurrences)
Last logged: 9:42:36 AM

Detected that custom integration 'smartrent' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/smartrent/__init__.py, line 54: hass.async_add_job(, please create a bug report at https://github.com/ZacheryThomas/homeassistant-smartrent/issues

**Comment by ZacheryThomas** [comment]
Should be fixed when you download the latest release!
https://github.com/ZacheryThomas/homeassistant-smartrent/releases/tag/v0.4.6
