### ISSUE TITLE
Issue in home assistant logs - async_forward_entry_setup

### ISSUE THREAD

**Issue by sam2332** [ZacheryThomas/homeassistant-smartrent#28]
Errors found in logs:

Detected code that calls async_forward_entry_setup for integration, smartrent with title: :{my_user} and entry_id: {my_id}, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead. Please report this issue.

Detected code that calls async_forward_entry_setup for integration smartrent with title:{my_user} and entry_id:{my_id}, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

**Comment by ZacheryThomas** [comment]
Should be fixed when you download the latest release!
https://github.com/ZacheryThomas/homeassistant-smartrent/releases/tag/v0.4.6
