### ISSUE TITLE
Issue in home assistant logs - ClimateEntityFeature

### ISSUE THREAD

**Issue by sam2332** [ZacheryThomas/homeassistant-smartrent#29]
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:365
integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 9:42:27 AM (1 occurrences)
Last logged: 9:42:27 AM

Entity None (<class 'custom_components.smartrent.climate.SmartrentThermostat'>) implements HVACMode(s): heat, cool, off, heat_cool and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/ZacheryThomas/homeassistant-smartrent/issues

**Comment by ZacheryThomas** [comment]
This appears to be the same warning found in this issue: https://github.com/ZacheryThomas/homeassistant-smartrent/issues/24

Gonna close this one out in favor of tracking the progress at the original issue
