### ISSUE TITLE
Incompatible with Homeassistant 2024.12 due to new Python version

### ISSUE THREAD

**Issue by Evanito** [ZacheryThomas/homeassistant-smartrent#32]
Integration fails to start, logs below:
```
Logger: homeassistant.setup
Source: setup.py:269
First occurred: 9:13:46 PM (1 occurrences)
Last logged: 9:13:46 PM

Setup failed for custom integration 'smartrent': Requirements for smartrent not found: ['smartrent-py==0.4.4'].
```
```
Logger: homeassistant.util.package
Source: util/package.py:152
First occurred: 9:13:43 PM (3 occurrences)
Last logged: 9:13:46 PM

Unable to install package smartrent-py==0.4.4: × No solution found when resolving dependencies: ╰─▶ Because smartrent-py==0.4.4 depends on websockets>=11.0.1,<12.0.0 and websockets>=13.1, we can conclude that smartrent-py==0.4.4 cannot be used. And because you require smartrent-py==0.4.4, we can conclude that your requirements are unsatisfiable.
```

**Comment by Evanito** [comment]
Looks like you already fixed this in https://github.com/ZacheryThomas/smartrent-py/releases/tag/v0.4.5 and just need to update manifest.json to point to the new version number.

**Comment by anthonymkz** [comment]
> Looks like you already fixed this in https://github.com/ZacheryThomas/smartrent-py/releases/tag/v0.4.5 and just need to update [manifest.json](https://github.com/ZacheryThomas/homeassistant-smartrent/blob/main/custom_components/smartrent/manifest.json#L13C6-L13C18) to point to the new version number. 

I submitted a pull request with the fix last night. Just waiting on the maintainer to approve it. In the meantime, if you update your own manifest.json and restart home assistant it will fix the issue.

**Comment by ZacheryThomas** [comment]
Got that new release out!
https://github.com/ZacheryThomas/homeassistant-smartrent/releases/tag/v0.4.7

Let me know if there are any issues etc

**Comment by anthonymkz** [comment]
Awesome! Seems to be working great.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
