### ISSUE TITLE
Sensors

### ISSUE THREAD

**Issue by Eclipseop** [ZacheryThomas/homeassistant-smartrent#5]
Would be nice to have the Lock/Climate/etc entities have sensors as well so they can be displayed differently.

Ie: if you want to display the lock status, you can't, or get the current temperature from the thermostat, etc. everything is locked behind its specific entity inside HA.

**Comment by ZacheryThomas** [comment]
Starting to work on this a bit now! Looking at adding a sensor for `humidity` and `current_temp` for climate related stuff, and `locked` and `notification` stuff for locks.
